scope: perf
time_limit: 1800
script_args:
  # All arguments referenced in the script string must be specified here.
  # Arguments not referenced in the script string must have the 'arg' field specified.
  # See jet/core/configs.py for the specification of the configuration class
  workspace:
    value: /workspace/bionemo2
    key_segment: False
  data_path:
    value: /data/20240809_uniref_2024_03/data
    key_segment: False
  model: esm2
  variant: train
  config_name: 650M
  precision: bf16-mixed
  max_steps: 200
  gpus: 8
  acc_grad: 1
  products:
    - nodes: 1
      batch_size: 16
      pp: 1
      tp: 1
    - nodes: 2
      batch_size: 16
      pp: 2
      tp: 1
    - nodes: 2
      batch_size: 16
      pp: 1
      tp: 2
    - nodes: 2
      batch_size: 16
      pp: 1
      tp: 1
script: |-
  WANDB_API_KEY=$BIONEMO_WANDB_API_KEY ${variant}_${model} \
    --train-cluster-path=${data_path}/train_clusters.parquet \
    --train-database-path=${data_path}/train.db \
    --valid-cluster-path=${data_path}/valid_clusters.parquet \
    --valid-database-path=${data_path}/validation.db \
    --micro-batch-size=${batch_size} \
    --num-nodes=${nodes} \
    --num-gpus=${gpus} \
    --val-check-interval=50 \
    --limit-val-batches=1 \
    --num-steps=${max_steps} \
    --min-seq-length=1024 \
    --max-seq-length=1024 \
    --num-layers=33 \
    --hidden-size=1280 \
    --num-attention-heads=20 \
    --ffn-hidden-size=5120 \
    --create-tensorboard-logger \
    --experiment-name=${batch_size}bs_${nodes}node_${gpus}gpu_${max_steps}s_${precision}prec \
    --result-dir=${tensorboard_dir} \
    --wandb-project=${wandb_project_name} \
    --wandb-group=${model}_${variant}_${config_name}__${target} \
    --wandb-job-type=${pipeline_label} \
    --log-every-n-steps=10 \
    --accumulate-grad-batches=${acc_grad} \
    --pipeline-model-parallel-size=${pp} \
    --tensor-model-parallel-size={tp} \
    --disable-checkpointing;
